all: funPointer funPointerV1 funPointerV2 funPointerV3 funPointerV4 funPointerV5
	gcc funPointer.c -o funPointer
	gcc funPointerV1.c -o funPointerV1
	gcc funPointerV2.c -o funPointerV2
	g++ funPointerV3.cpp -o funPointerV3	
	g++ funPointerV4.cpp -o funPointerV4
	g++ funPointerV5.cpp -o funPointerV5

clean:
	rm -rf funPointer funPointerV1 funPointerV2 funPointerV3 funPointerV4 funPointerV5
